### ISSUE TITLE
Imported ptus have inconsistent number of bins (Las-X or ptufile related?)

### ISSUE THREAD

**Issue by Jintram** [cgohlke/ptufile#1]
Dear Christoph, 

Many thanks for your work, I'm currently looking at FLIM data and it's really nice to be able to import it in Python rather effortlessly.

I have two questions, which I'm not sure are (fully) related to the ptufile library, or relate more to the technicalities behind Leica's software and microscope. So please don't feel obliged to answer.

I took FLIM data using the Leica Stellaris 8 platform, and exported .ptu files using their Las-X software for further custom processing in Python. I have multiple samples on which I performed measurements. The measurements are always according to the same settings. I imported files with the ptufile library.

Questions:
1. For different samples, the number of time bins appear to be different. (Even though the frequency was always 40 MHz and other settings also equal.) E.g. these are the shapes of two ptu objects that I imported using the ptufile library.
(1, 512, 512, 4, 266)
(1, 512, 512, 4, 282)
How can this be, why are there 266 bins in one sample and 282 bins in the other?
Importantly, (i) are the bin edges chosen differently and do they cover the same amount of time, or (ii) are there bins (perhaps with no detected photons) "missing" (and can bins with a value of zero thus be padded to the end of the measurement)?

The latter would actually be my guess, ie there might be missing bins for samples where there are "bins" that do not have photon counts, and therefor dropped. In which case I can introduce bins with zero counts to "pad" the data until dimensions are consistent among samples.

2. This question is definitely more Leica related, but perhaps you happen to know (and I have the feeling it is somewhat related to the above issue).
For most samples, the different channels are all exported to the same file, as reflected above by the fact that the 4th dimension has a length of 4 (I have 4 channels). For some samples, I however get 4 files for the single sample, e.g. sample "H1":
H1_seq1.ptu
H1_seq2.ptu
H1_seq3.ptu
H1_seq4.ptu
When imported with ptufile, these files show the following shapes:
(3, 512, 512, 1, X)
(3, 512, 512, 2, X)
(3, 512, 512, 3, X)
(3, 512, 512, 4, X)
Strikingly, these show:
a) Empty channels. E.g. channel seq4 only has values in channel 4, other channels show only zeroes, seq3 only has values in channel 3, and zeroes otherwise, and so forth.
b) I don't understand why there are now suddenly 3 entries along the first dimension, which also all hold data (ie for each of ptu[0,..], ptu[1,..], ptu[2,..] there's data; similar but slightly different).
*
I cannot look into ptu files, and my initial guess was that the seqX files represent the four channels I used. If so, the unexpected behavior I observe might also be partially due to ptufile, in case (I'm now hypothesising) data for each of the channels are indeed divided over 4 ptu files by Las-X, but ptufile introduces zeros if it only has information for say channel 3, and padds the other dimensions with zeros (this hypothesis is consistent with the file sizes of the seqX files, as the size of seq4 is not larger than seq3, suggesting the information is not redundant but rather specific for a channel).

Any input regarding these questions would be highly appreciated. Many thanks in advance!

All the best, Martijn

**Comment by Jintram** [comment]
After writing this question and talking to a collegue I realized there might actually be a setting in the ptufile import function, and indeed there is.

From your sourcecode (`class PtuFile(PqFile)`):
```
    Parameters:
        file:
            File name or seekable binary stream.
        trimdims:
            Axes to trim. The default is ``'TCH'``:

            - ``'T'``: remove incomplete first or last frame.
            - ``'C'``: remove trailing channels not containing photons.
              Else use record type's default :py:attr:`number_channels_max`.
            - ``'H'``: remove trailing delay-time bins not containing photons.
              Else use record type's default :py:attr:`number_bins_max`.
```

If I change trimdims to "TC", indeed, all number of bins are equal (and set to 4096).

I still don't understand this though, as previously I was pretty sure my 250-270 bins (which were in fact trimmed) covered most of the 25 ns measurement time window corresponding to 40 MHz. What time window do the 4096 bins cover?

**Comment by cgohlke** [comment]
Hi @Jintram,

the PTU files exported from Leica software are special in many ways, some of which we are still trying to make sense of.

> 1. For different samples, the number of time bins appear to be different.

This is because ptufile by default returns all data/records/photons found in the file and trims the bins, channel, and time dimensions at the highest indices found. It is surprising to get data beyond what is expected from the frequency, but that is what is encoded in the files. I think this is due to some slight variations/inaccuracies in syncing macro and micro clocks. Or it could be a bug in the Leica software. Anyway, ptufile has many options to control which parts are decoded:

https://github.com/cgohlke/ptufile/blob/ae65544920bdd70d22a16e920ca5641bbeed4a6a/ptufile/ptufile.py#L1834-L1914

In your case you want to set `dtime=0`, which will return `number_bins_in_period` bins.

> For some samples, I however get 4 files for the single sample, e.g. sample "H1":
> When imported with ptufile, these files show the following shapes:

I don't know why Leica exports some measurements to separate files. As for ptufile returning different shapes, the situation is similar to the histogram bins. Ptufile scans the encoded data for the highest channel with photons. It does not determine if some lower channels are empty (same for histogram bins). To work around that, specify the channel to load, for example, `channel=3` for `H1_seq4.ptu`.

>  I don't understand why there are now suddenly 3 entries along the first dimension

Ptufile detects 3 time frames based on frame and line markers in the encoded data. You can integrate the time frames using the `frame` parameter, for example, `frame=-1` will integrate all frames into one.

> What time window do the 4096 bins cover?

This is the maximum number of bins the hardware/firmware can collect. Similar, if you do not trim the channel axis, ptufile will return the maximum number of channels the hardware supports.

Btw, to preview the image and metadata contained in a PTU file, run `python -m ptufile filename.ptu`

Hope this answer your questions.

**Comment by Jintram** [comment]
Dear Christoph,

Many thanks for this extensive reply, this is hugely helpful to understanding the details of analyzing the .ptu files and using ptufile!

Just to organize my thoughts (and perhaps also useful for other readers rather new to this analysis), let me summarize;

So indeed ptufile trims the number of bins if they are empty. Using your suggested command `python -m ptufile filename.ptu` (very useful) gives me the important information I need to properly analyze my data. In my case:

```
frequency: 39010000.0
global_resolution: 2.563445270443476e-08
number_bins_in_period: 264
```

This tells me that my frequency is actually not precisely 40 MHz, but 39.01 MHz, and that the time period over which photons are captured is 25.6 ns, and that 264 bins are spaced across that period. With potentially tail bins lacking or even additional bins added to the end -- this latter phenomenon being confusing as you point out. 

Using `my_ptu = PtuFile(base_filepath + '.ptu')` and `dir(my_ptu)` I can also see that these parameters are directly available in Python through 

```
>>> my_ptu.frequency
39010000.0
>>> my_ptu.global_resolution
2.563445270443476e-08
>>> my_ptu.number_bins_in_period
264
```

which is very convenient.

Anyways my approach will thus be to either zero-pad data to 264 bins and ignore bins >264.

You suggest I can also have ptufile return the appropriate number of bins directly by using `dtime=0`. Before I've been using the function `my_ptu = PtuFile(base_filepath + '.ptu')` to read my files (I realize now this initializes an object so it's not a function technically I guess), which doesn't allow for the parameter dtime to be passed. However, if I use `my_ptu_img = ptufile.imread(base_filepath + '.ptu', dtime=0)`, I indeed get back the expected dimensions based on above information.

```
>>> my_ptu_img.shape
(1, 512, 512, 4, 264)
```

This makes my life much easier.

> I don't know why Leica exports some measurements to separate files. (..) To work around that, specify the channel to load (..)

> You can integrate the time frames using the frame parameter, for example, frame=-1 will integrate all frames into one.

This behavior indeed remains puzzling, but many thanks for the suggested workarounds!

(I also realized I indeed have three line repetitions in the measurement, so it makes sense that there are 3 frame in the first dimensions, but it's weird that these then don't show up separately in my other files -- but I can now work around this anyways.)

I will also try to delve more into your code to understand options I have to read in these files (e.g. use `imread` vs. `PtuFile`).

Again many thanks for your time and thanks for this tool.

**Comment by cgohlke** [comment]
Hi @Jintram,

your summary looks correct. 

`ptufile.imread()` is a convenience wrapper for `ptufile.PtuFile().decode_image()`. The advantage of using the `PtuFile` class is that it gives access to all metadata and the decoded records in the file. 

Not returning the channels without photons is on the [TODO](https://github.com/cgohlke/ptufile/blob/ae65544920bdd70d22a16e920ca5641bbeed4a6a/ptufile/ptufile.py#L1221-L1226) list. There is a metadata tag for that (`HWInpChan_Enabled`) but one can't rely on it being present.

**Comment by cgohlke** [comment]
> a) Empty channels. E.g. channel seq4 only has values in channel 4, other channels show only zeroes, seq3 only has values in channel 3, and zeroes otherwise, and so forth.

Ptufile v2024.10.10 also trims leading empty channels.

**Comment by Jintram** [comment]
> > a) Empty channels. E.g. channel seq4 only has values in channel 4, other channels show only zeroes, seq3 only has values in channel 3, and zeroes otherwise, and so forth.
> 
> Ptufile v2024.10.10 also trims leading empty channels.

Thanks for incorporating this!
